services:
  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: deploy-api
    ports:
      - "8000:8000"
    volumes:
      - ../backend/app/static:/app/app/static
    environment:
      - BASE_URL=http://localhost:8000
    networks:
      - app_net

  db:
    image: postgres:14
    container_name: deploy-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongpass
    ports:
      - "5432:5432"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge